use std::str::FromStr;

use bdk_sqlite::Store;
use bdk_wallet::{CreateParams, KeychainKind, PersistedWallet, Wallet};
use bitcoin::Network;
use miniscript::descriptor::DescriptorPublicKey;
use miniscript::Descriptor;

use crate::config::ScanConfig;
use crate::error::VersoError;
use crate::storage;

/// Holds either an ephemeral (in-memory) wallet or a persisted wallet.
///
/// For the `Persisted` variant the [`Store`] (SQLite connection pool) is kept
/// alongside the wallet so that `persist_if_needed` can flush staged changes
/// back to disk after a sync.
pub enum WalletKind {
    Ephemeral(Wallet),
    Persisted(PersistedWallet<Store>, Store),
}

impl WalletKind {
    pub(crate) fn as_mut_wallet(&mut self) -> &mut Wallet {
        match self {
            WalletKind::Ephemeral(w) => w,
            // PersistedWallet<Store> implements DerefMut<Target=Wallet>.
            WalletKind::Persisted(pw, _store) => pw,
        }
    }

    pub fn as_wallet(&self) -> &Wallet {
        match self {
            WalletKind::Ephemeral(w) => w,
            // PersistedWallet<Store> implements Deref<Target=Wallet>.
            WalletKind::Persisted(pw, _store) => pw,
        }
    }

    /// Persist any staged wallet changes to the underlying store.
    ///
    /// For ephemeral wallets this is a no-op.  For persisted wallets it calls
    /// [`PersistedWallet::persist_async`] which writes the staged changeset
    /// (produced by `full_sync`) to the SQLite database.
    pub async fn persist_if_needed(&mut self) -> Result<(), VersoError> {
        match self {
            WalletKind::Ephemeral(_) => Ok(()),
            WalletKind::Persisted(wallet, store) => wallet
                .persist_async(store)
                .await
                .map(|_| ())
                .map_err(|e| VersoError::Storage(e.to_string())),
        }
    }
}

pub struct Scanner {
    pub(crate) wallet: WalletKind,
}

impl Scanner {
    /// Consume the scanner and return the inner wallet kind.
    pub fn into_wallet(self) -> WalletKind {
        self.wallet
    }

    /// Parse 1 or 2 descriptor strings into an (external, internal) pair.
    ///
    /// If a single descriptor containing `/0/*` is provided, the internal
    /// descriptor is auto-generated by replacing `/0/*` with `/1/*`.
    /// If 2 descriptors are provided, they are used as-is.
    pub fn parse_descriptors(
        descriptors: &[String],
        network: Network,
    ) -> Result<(String, String), VersoError> {
        match descriptors {
            [] => Err(VersoError::DescriptorParse(
                "at least one descriptor is required".into(),
            )),
            [single] => {
                // Auto-wrap bare extended keys (xpub/ypub/zpub/tpub/upub/vpub)
                // that were passed without a descriptor template.
                let external = auto_wrap_key(single.trim())?;
                if !external.contains("/0/*") {
                    return Err(VersoError::DescriptorParse(
                        "cannot auto-derive internal keychain: descriptor has no /0/* wildcard path"
                            .to_string(),
                    ));
                }
                let internal = external.replace("/0/*", "/1/*");
                validate_descriptor(&external, network)?;
                validate_descriptor(&internal, network)?;
                Ok((external, internal))
            }
            [ext, int] => {
                let ext = auto_wrap_key(ext.trim())?;
                let int = auto_wrap_key(int.trim())?;
                validate_descriptor(&ext, network)?;
                validate_descriptor(&int, network)?;
                Ok((ext, int))
            }
            _ => Err(VersoError::DescriptorParse(
                "at most two descriptors are supported (external and internal)".into(),
            )),
        }
    }

    /// Create a new Scanner from the given configuration.
    ///
    /// Parses descriptors, opens (or creates) the wallet, then reveals
    /// addresses up to `config.derivation_limit` for both keychains.
    pub async fn new(config: &ScanConfig) -> Result<Self, VersoError> {
        let (ext, int) = Self::parse_descriptors(&config.descriptors, config.network)?;

        let mut wallet_kind = if config.ephemeral {
            // ext and int are owned Strings, satisfying 'static.
            let wallet = CreateParams::new(ext.clone(), int.clone())
                .network(config.network)
                .create_wallet_no_persist()
                .map_err(|e| VersoError::Wallet(e.to_string()))?;
            WalletKind::Ephemeral(wallet)
        } else {
            let data_dir = config.data_dir.as_deref().ok_or_else(|| {
                VersoError::InvalidConfig("data_dir must be set when ephemeral is false".into())
            })?;
            let db_path = storage::resolve_db_path(data_dir, &ext, &int, config.network);
            let (wallet, store) =
                storage::open_wallet(&ext, &int, config.network, &db_path).await?;
            WalletKind::Persisted(wallet, store)
        };

        // Reveal addresses up to derivation_limit for both keychains.
        // Consume the iterator to apply the changes.
        let limit = config.derivation_limit;
        {
            let w = wallet_kind.as_mut_wallet();
            let _ = w.reveal_addresses_to(KeychainKind::External, limit).count();
            let _ = w.reveal_addresses_to(KeychainKind::Internal, limit).count();
        }

        Ok(Scanner {
            wallet: wallet_kind,
        })
    }
}

/// If the input looks like a bare extended public key (no descriptor wrapper),
/// normalize its version bytes to standard xpub/tpub (miniscript only understands
/// those) and auto-wrap as `wpkh(key/0/*)`.
///
/// SLIP-132 defines alternative version prefixes that encode script-type intent:
///   mainnet: ypub (P2SH-P2WPKH), zpub (P2WPKH)  → converted to xpub
///   testnet: upub (P2SH-P2WPKH), vpub (P2WPKH)  → converted to tpub
/// xpub/tpub are left unchanged.
fn auto_wrap_key(s: &str) -> Result<String, VersoError> {
    let bare_prefixes = ["xpub", "ypub", "zpub", "tpub", "upub", "vpub"];
    let is_bare = bare_prefixes.iter().any(|p| s.starts_with(p)) && !s.contains('(');
    if is_bare {
        let normalized = normalize_xpub_version(s)?;
        Ok(format!("wpkh({}/0/*)", normalized))
    } else {
        Ok(s.to_string())
    }
}

/// Convert SLIP-132 extended key version bytes (ypub/zpub/upub/vpub) to the
/// standard BIP-32 xpub/tpub that miniscript can parse.
///
/// The on-disk encoding is base58check over 78 bytes:
///   [0..4]  version (4 bytes) ← we replace this
///   [4..78] depth, fingerprint, child_number, chain_code, pubkey
/// After swapping the version the rest of the payload is unchanged.
fn normalize_xpub_version(key: &str) -> Result<String, VersoError> {
    use bitcoin::hashes::{sha256d, Hash};

    // SLIP-132 → BIP-32 canonical version bytes
    const MAINNET_XPUB: [u8; 4] = [0x04, 0x88, 0xB2, 0x1E];
    const TESTNET_TPUB: [u8; 4] = [0x04, 0x35, 0x87, 0xCF];

    let canonical: Option<[u8; 4]> = if key.starts_with("ypub") || key.starts_with("zpub") {
        Some(MAINNET_XPUB)
    } else if key.starts_with("upub") || key.starts_with("vpub") {
        Some(TESTNET_TPUB)
    } else {
        None
    };

    let canonical = match canonical {
        None => return Ok(key.to_string()),
        Some(v) => v,
    };

    // base58::decode returns raw bytes INCLUDING the 4-byte checksum appended
    // at the end. Total length for an xpub is 78 payload + 4 checksum = 82 bytes.
    let raw = bitcoin::base58::decode(key)
        .map_err(|e| VersoError::DescriptorParse(format!("invalid extended key: {e}")))?;

    if raw.len() < 8 {
        return Err(VersoError::DescriptorParse("extended key too short".into()));
    }

    let payload = &raw[..raw.len() - 4];
    let provided_checksum = &raw[raw.len() - 4..];

    // Verify checksum before we do anything
    let expected = sha256d::Hash::hash(payload);
    if provided_checksum != &expected[..4] {
        return Err(VersoError::DescriptorParse(
            "invalid extended key: checksum mismatch".into(),
        ));
    }

    // Swap version bytes and recompute checksum
    let mut new_payload = payload.to_vec();
    new_payload[..4].copy_from_slice(&canonical);
    let new_hash = sha256d::Hash::hash(&new_payload);
    new_payload.extend_from_slice(&new_hash[..4]);

    Ok(bitcoin::base58::encode(&new_payload))
}

/// Validate a descriptor string using miniscript.
fn validate_descriptor(desc: &str, _network: Network) -> Result<(), VersoError> {
    // Strip checksum if present (miniscript parser requires it absent or valid)
    let desc_no_checksum = if let Some(pos) = desc.rfind('#') {
        &desc[..pos]
    } else {
        desc
    };

    Descriptor::<DescriptorPublicKey>::from_str(desc_no_checksum)
        .map_err(|e| VersoError::DescriptorParse(e.to_string()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    // Standard BDK testnet extended public key (from BDK's own test suite)
    const TPUB: &str = "tpubD6NzVbkrYhZ4XHndKkuB8FifXm8r5FQHwrN6oZuWCz13qb93rtgKvD4PQsqC4HP4yhV3tA2fqr2RbY5mNXfM7RxXUoeABoDtsFUq2zJq6YK";

    fn ext_desc() -> String {
        format!("wpkh({}/0/*)", TPUB)
    }

    fn int_desc() -> String {
        format!("wpkh({}/1/*)", TPUB)
    }

    #[test]
    fn test_invalid_descriptor_returns_error() {
        let bad = vec!["not_a_descriptor".to_string()];
        let result = Scanner::parse_descriptors(&bad, Network::Regtest);
        assert!(
            matches!(result, Err(VersoError::DescriptorParse(_))),
            "Expected DescriptorParse error, got: {:?}",
            result
        );
    }

    #[test]
    fn test_auto_derive_internal_descriptor() {
        let ext = ext_desc();
        let descriptors = vec![ext.clone()];
        let result = Scanner::parse_descriptors(&descriptors, Network::Testnet);
        assert!(result.is_ok(), "Expected Ok, got: {:?}", result);
        let (got_ext, got_int) = result.unwrap();
        assert_eq!(got_ext, ext);
        assert_eq!(got_int, int_desc(), "Internal descriptor should use /1/*");
    }

    #[test]
    fn test_two_descriptors_used_directly() {
        let ext = ext_desc();
        let int = int_desc();
        let descriptors = vec![ext.clone(), int.clone()];
        let result = Scanner::parse_descriptors(&descriptors, Network::Testnet);
        assert!(result.is_ok(), "Expected Ok, got: {:?}", result);
        let (got_ext, got_int) = result.unwrap();
        assert_eq!(got_ext, ext);
        assert_eq!(got_int, int);
    }

    #[test]
    fn test_single_key_no_path_uses_same_for_both() {
        // A descriptor with no /0/* wildcard should now return an error,
        // because we cannot safely auto-derive the internal keychain.
        let desc = format!("wpkh({}/1/2/*)", TPUB);
        let descriptors = vec![desc.clone()];
        let result = Scanner::parse_descriptors(&descriptors, Network::Testnet);
        assert!(
            matches!(result, Err(VersoError::DescriptorParse(_))),
            "Expected DescriptorParse error when no /0/* path present, got: {:?}",
            result
        );
    }

    #[test]
    fn test_empty_descriptors_returns_error() {
        let result = Scanner::parse_descriptors(&[], Network::Regtest);
        assert!(
            matches!(result, Err(VersoError::DescriptorParse(_))),
            "Expected DescriptorParse error for empty input"
        );
    }

    #[tokio::test]
    async fn test_scanner_new_ephemeral() {
        use crate::config::BackendConfig;
        let config = ScanConfig {
            descriptors: vec![ext_desc(), int_desc()],
            network: Network::Testnet,
            backend: BackendConfig::Esplora {
                url: "https://mempool.space/testnet/api".to_string(),
            },
            known_risky_txids: None,
            known_exchange_txids: None,
            derivation_limit: 10,
            data_dir: None,
            ephemeral: true,
            progress_tx: None,
        };
        let scanner = Scanner::new(&config).await;
        assert!(
            scanner.is_ok(),
            "Scanner::new should succeed in ephemeral mode: {:?}",
            scanner.err()
        );
    }
}
