use std::str::FromStr;

use bdk_sqlite::Store;
use bdk_wallet::{CreateParams, KeychainKind, PersistedWallet, Wallet};
use bitcoin::Network;
use miniscript::Descriptor;
use miniscript::descriptor::DescriptorPublicKey;

use crate::config::ScanConfig;
use crate::error::VersoError;
use crate::storage;

/// Holds either an ephemeral (in-memory) wallet or a persisted wallet.
pub enum WalletKind {
    Ephemeral(Wallet),
    Persisted(PersistedWallet<Store>),
}

impl WalletKind {
    pub(crate) fn as_mut_wallet(&mut self) -> &mut Wallet {
        match self {
            WalletKind::Ephemeral(w) => w,
            WalletKind::Persisted(pw) => pw,
        }
    }

    pub fn as_wallet(&self) -> &Wallet {
        match self {
            WalletKind::Ephemeral(w) => w,
            WalletKind::Persisted(pw) => pw,
        }
    }
}

pub struct Scanner {
    pub wallet: WalletKind,
}

impl Scanner {
    /// Parse 1 or 2 descriptor strings into an (external, internal) pair.
    ///
    /// If a single descriptor containing `/0/*` is provided, the internal
    /// descriptor is auto-generated by replacing `/0/*` with `/1/*`.
    /// If 2 descriptors are provided, they are used as-is.
    pub fn parse_descriptors(
        descriptors: &[String],
        network: Network,
    ) -> Result<(String, String), VersoError> {
        match descriptors {
            [] => Err(VersoError::DescriptorParse(
                "at least one descriptor is required".into(),
            )),
            [single] => {
                let external = single.clone();
                if !single.contains("/0/*") {
                    return Err(VersoError::DescriptorParse(
                        "cannot auto-derive internal keychain: descriptor has no /0/* wildcard path"
                            .to_string(),
                    ));
                }
                let internal = single.replace("/0/*", "/1/*");
                validate_descriptor(&external, network)?;
                validate_descriptor(&internal, network)?;
                Ok((external, internal))
            }
            [ext, int, ..] => {
                validate_descriptor(ext, network)?;
                validate_descriptor(int, network)?;
                Ok((ext.clone(), int.clone()))
            }
        }
    }

    /// Create a new Scanner from the given configuration.
    ///
    /// Parses descriptors, opens (or creates) the wallet, then reveals
    /// addresses up to `config.derivation_limit` for both keychains.
    pub async fn new(config: &ScanConfig) -> Result<Self, VersoError> {
        let (ext, int) = Self::parse_descriptors(&config.descriptors, config.network)?;

        let mut wallet_kind = if config.ephemeral {
            // ext and int are owned Strings, satisfying 'static.
            let wallet = CreateParams::new(ext.clone(), int.clone())
                .network(config.network)
                .create_wallet_no_persist()
                .map_err(|e| VersoError::Wallet(e.to_string()))?;
            WalletKind::Ephemeral(wallet)
        } else {
            let data_dir = config.data_dir.as_deref().ok_or_else(|| {
                VersoError::InvalidConfig(
                    "data_dir must be set when ephemeral is false".into(),
                )
            })?;
            let db_path = storage::resolve_db_path(data_dir, &ext, config.network);
            let wallet =
                storage::open_wallet(&ext, &int, config.network, &db_path).await?;
            WalletKind::Persisted(wallet)
        };

        // Reveal addresses up to derivation_limit for both keychains.
        // Consume the iterator to apply the changes.
        let limit = config.derivation_limit;
        {
            let w = wallet_kind.as_mut_wallet();
            let _ = w
                .reveal_addresses_to(KeychainKind::External, limit)
                .count();
            let _ = w
                .reveal_addresses_to(KeychainKind::Internal, limit)
                .count();
        }

        Ok(Scanner { wallet: wallet_kind })
    }
}

/// Validate a descriptor string using miniscript.
fn validate_descriptor(desc: &str, _network: Network) -> Result<(), VersoError> {
    // Strip checksum if present (miniscript parser requires it absent or valid)
    let desc_no_checksum = if let Some(pos) = desc.rfind('#') {
        &desc[..pos]
    } else {
        desc
    };

    Descriptor::<DescriptorPublicKey>::from_str(desc_no_checksum)
        .map_err(|e| VersoError::DescriptorParse(e.to_string()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    // Standard BDK testnet extended public key (from BDK's own test suite)
    const TPUB: &str = "tpubD6NzVbkrYhZ4XHndKkuB8FifXm8r5FQHwrN6oZuWCz13qb93rtgKvD4PQsqC4HP4yhV3tA2fqr2RbY5mNXfM7RxXUoeABoDtsFUq2zJq6YK";

    fn ext_desc() -> String {
        format!("wpkh({}/0/*)", TPUB)
    }

    fn int_desc() -> String {
        format!("wpkh({}/1/*)", TPUB)
    }

    #[test]
    fn test_invalid_descriptor_returns_error() {
        let bad = vec!["not_a_descriptor".to_string()];
        let result = Scanner::parse_descriptors(&bad, Network::Regtest);
        assert!(
            matches!(result, Err(VersoError::DescriptorParse(_))),
            "Expected DescriptorParse error, got: {:?}",
            result
        );
    }

    #[test]
    fn test_auto_derive_internal_descriptor() {
        let ext = ext_desc();
        let descriptors = vec![ext.clone()];
        let result = Scanner::parse_descriptors(&descriptors, Network::Testnet);
        assert!(result.is_ok(), "Expected Ok, got: {:?}", result);
        let (got_ext, got_int) = result.unwrap();
        assert_eq!(got_ext, ext);
        assert_eq!(got_int, int_desc(), "Internal descriptor should use /1/*");
    }

    #[test]
    fn test_two_descriptors_used_directly() {
        let ext = ext_desc();
        let int = int_desc();
        let descriptors = vec![ext.clone(), int.clone()];
        let result = Scanner::parse_descriptors(&descriptors, Network::Testnet);
        assert!(result.is_ok(), "Expected Ok, got: {:?}", result);
        let (got_ext, got_int) = result.unwrap();
        assert_eq!(got_ext, ext);
        assert_eq!(got_int, int);
    }

    #[test]
    fn test_single_key_no_path_uses_same_for_both() {
        // A descriptor with no /0/* wildcard should now return an error,
        // because we cannot safely auto-derive the internal keychain.
        let desc = format!("wpkh({}/1/2/*)", TPUB);
        let descriptors = vec![desc.clone()];
        let result = Scanner::parse_descriptors(&descriptors, Network::Testnet);
        assert!(
            matches!(result, Err(VersoError::DescriptorParse(_))),
            "Expected DescriptorParse error when no /0/* path present, got: {:?}",
            result
        );
    }

    #[test]
    fn test_empty_descriptors_returns_error() {
        let result = Scanner::parse_descriptors(&[], Network::Regtest);
        assert!(
            matches!(result, Err(VersoError::DescriptorParse(_))),
            "Expected DescriptorParse error for empty input"
        );
    }

    #[tokio::test]
    async fn test_scanner_new_ephemeral() {
        use crate::config::BackendConfig;
        let config = ScanConfig {
            descriptors: vec![ext_desc(), int_desc()],
            network: Network::Testnet,
            backend: BackendConfig::Esplora {
                url: "https://mempool.space/testnet/api".to_string(),
            },
            known_risky_txids: None,
            known_exchange_txids: None,
            derivation_limit: 10,
            data_dir: None,
            ephemeral: true,
            progress_tx: None,
        };
        let scanner = Scanner::new(&config).await;
        assert!(
            scanner.is_ok(),
            "Scanner::new should succeed in ephemeral mode: {:?}",
            scanner.err()
        );
    }
}
